name: Scan

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup .npmrc & npm install
        run: |
          cat <<EOF > ".npmrc"
          @neverendingsupport:registry=https://registry.dev.nes.herodevs.com/npm/pkg/
          //registry.dev.nes.herodevs.com/npm/pkg/:_authToken="${{ secrets.NES_ACCESS_TOKEN_HOW_SCANNER_WORK }}"
          EOF
          npm install

      - name: Snyk Scan
        uses: neverendingsupport/actions/snyk@v1
        with:
          snykOrgId: ${{ secrets.SNYK_ORG_ID }}
          snykToken: ${{ secrets.SNYK_TOKEN }}
          snykThreshold: low

